/* Mastery cloud sync v2 - timestamp-based two-way sync, no data loss. */ (function(){ var SUPABASE_URL="https://rkvrwtjyeglgbkaxagig.supabase.co"; var SUPABASE_KEY="sb_publishable_RIuSyw9WrbLbjr0gJEEYKQ_CujEO3Jg"; var SYNC_KEYS=["mastery_day","mastery_archive","mastery_v6","mastery_lockin_day","mastery_scores","mastery_theme"]; var TS_KEY="mastery_sync_ts"; var sb=null,user=null,pushTimer=null,pulling=false,pushing=false,statusEl=null;
                                                                                      function loadScript(src){ return new Promise(function(res,rej){ var s=document.createElement("script"); s.src=src; s.onload=res; s.onerror=rej; document.head.appendChild(s); }); }
                                                                                      function snapshot(){ var o={}; for(var i=0;i<SYNC_KEYS.length;i++){ var k=SYNC_KEYS[i]; var v=localStorage.getItem(k); if(v!==null) o[k]=v; } return o; }
                                                                                      function sameData(a,b){ if(!a||!b) return false; for(var i=0;i<SYNC_KEYS.length;i++){ var k=SYNC_KEYS[i]; if((a[k]||"")!==(b[k]||"")) return false; } return true; }
                                                                                      function applySnapshot(o){ if(!o) return; pulling=true; try{ for(var k in o){ if(o.hasOwnProperty(k)&&SYNC_KEYS.indexOf(k)>=0){ localStorage.setItem(k,o[k]); } } } finally { pulling=false; } }
                                                                                      function setStatus(t){ if(statusEl) statusEl.textContent=t; }
                                                                                      function schedulePush(){ if(!user) return; if(pushTimer) clearTimeout(pushTimer); setStatus("Saving..."); pushTimer=setTimeout(function(){ pushTimer=null; pushNow(); },1000); }
                                                                                      function pushNow(){ if(!user||!sb) return; pushing=true; var ts=new Date().toISOString(); var payload={ user_id:user.id, data:snapshot(), updated_at:ts }; return sb.from("user_data").upsert(payload,{onConflict:"user_id"}).then(function(r){ pushing=false; if(r.error){ setStatus("Save failed: "+r.error.message); console.warn("[sync] push error",r.error.message); } else { localStorage.setItem(TS_KEY,ts); setStatus("Saved"); } }); }
                                                                                      function pull(){ if(!user||!sb||pushing||pushTimer) return Promise.resolve(); return sb.from("user_data").select("data,updated_at").eq("user_id",user.id).maybeSingle().then(function(r){ if(r.error){ setStatus("Sync error: "+r.error.message); console.warn("[sync] pull error",r.error.message); return; } if(r.data&&r.data.data&&Object.keys(r.data.data).length){ var remoteTs=r.data.updated_at||""; var localTs=localStorage.getItem(TS_KEY)||""; var differs=!sameData(snapshot(),r.data.data); if(differs&&remoteTs>localTs){ applySnapshot(r.data.data); localStorage.setItem(TS_KEY,remoteTs); setStatus("Updated from cloud"); window.dispatchEvent(new CustomEvent("mastery-sync-applied")); if(!sessionStorage.getItem("mastery_just_synced")){ sessionStorage.setItem("mastery_just_synced","1"); location.reload(); } } else { localStorage.setItem(TS_KEY,remoteTs); setStatus("Synced"); } } else { pushNow(); setStatus("Backed up"); } }); }
                                                                                      function creds(){ return { email:(document.getElementById("csEmail").value||"").trim(), password:document.getElementById("csPass").value }; }
                                                                                      function doSignup(){ var c=creds(); if(!c.email||!c.password){ setStatus("Enter email + password"); return; } setStatus("Creating..."); sb.auth.signUp({email:c.email,password:c.password}).then(function(r){ if(r.error) setStatus(r.error.message); else setStatus("Check your email to confirm, then sign in"); }); }
                                                                                      function doLogin(){ var c=creds(); if(!c.email||!c.password){ setStatus("Enter email + password"); return; } setStatus("Signing in..."); sb.auth.signInWithPassword({email:c.email,password:c.password}).then(function(r){ if(r.error) setStatus(r.error.message); else onAuth(r.data.user); }); }
                                                                                      function doLogout(){ sb.auth.signOut().then(function(){ user=null; sessionStorage.removeItem("mastery_just_synced"); renderAuthState(); setStatus("Signed out"); }); }
                                                                                      function renderAuthState(){ var box=document.getElementById("cloudSyncBox"); if(!box) return; var out=box.querySelector("#csOut"); var form=box.querySelector("#csForm"); var who=box.querySelector("#csWho"); if(user){ if(out) out.style.display="block"; if(form) form.style.display="none"; if(who){ who.style.display="block"; who.textContent=user.email; } } else { if(out) out.style.display="none"; if(form) form.style.display="block"; if(who) who.style.display="none"; } }
                                                                                      function onAuth(u){ if(!u) return; user=u; renderAuthState(); setStatus("Signed in"); pull(); if(!window.__masteryPullTimer){ window.__masteryPullTimer=setInterval(function(){ if(user&&sb&&document.visibilityState==="visible"){ pull(); } },15000); } }
                                                                                      function buildBox(){ if(document.getElementById("cloudSyncBox")) return; var panel=document.querySelector("#settings-sheet .sheet-panel"); if(!panel) return; var mentorRow=null; var kids=panel.children; for(var i=0;i<kids.length;i++){ if(/Mentor Notes/.test(kids[i].textContent||"")){ mentorRow=kids[i]; break; } } var wrap=document.createElement("div"); wrap.id="cloudSyncBox"; wrap.style.cssText="margin:0 0 22px 0;padding:16px;border:1px solid rgba(0,0,0,0.08);border-radius:14px;background:rgba(0,0,0,0.02);";
                                                                                                          var h=''; h+='<div style="font-weight:700;font-size:16px;margin-bottom:2px;">Cloud Sync</div>';
                                                                                                          h+='<div id="csStatus" style="font-size:12px;color:#8a8a8a;margin-bottom:12px;">Not signed in</div>';
                                                                                                          h+='<div id="csWho" style="display:none;font-size:13px;font-weight:600;margin-bottom:10px;"></div>';
                                                                                                          h+='<div id="csForm" style="display:none;">';
                                                                                                          h+='<input id="csEmail" type="email" placeholder="Email" autocomplete="username" style="width:100%;box-sizing:border-box;margin-bottom:8px;padding:11px;border-radius:9px;border:1px solid rgba(0,0,0,0.15);font-size:14px;">';
                                                                                                          h+='<input id="csPass" type="password" placeholder="Password" autocomplete="current-password" style="width:100%;box-sizing:border-box;margin-bottom:10px;padding:11px;border-radius:9px;border:1px solid rgba(0,0,0,0.15);font-size:14px;">';
                                                                                                          h+='<div style="display:flex;gap:8px;">';
                                                                                                          h+='<button id="csLogin" style="flex:1;padding:11px;border:0;border-radius:9px;background:#4f8cff;color:#fff;font-weight:600;font-size:14px;cursor:pointer;">Sign in</button>';
                                                                                                          h+='<button id="csSignup" style="flex:1;padding:11px;border:0;border-radius:9px;background:rgba(0,0,0,0.06);color:inherit;font-weight:600;font-size:14px;cursor:pointer;">Sign up</button>';
                                                                                                          h+='</div></div>';
                                                                                                          h+='<button id="csOut" style="display:none;width:100%;padding:11px;border:0;border-radius:9px;background:rgba(0,0,0,0.06);color:inherit;font-weight:600;font-size:14px;cursor:pointer;">Sign out</button>';
                                                                                                          wrap.innerHTML=h; if(mentorRow){ panel.insertBefore(wrap,mentorRow); } else { panel.appendChild(wrap); } statusEl=wrap.querySelector("#csStatus"); wrap.querySelector("#csLogin").onclick=doLogin; wrap.querySelector("#csSignup").onclick=doSignup; wrap.querySelector("#csOut").onclick=doLogout; renderAuthState(); }
                                                                                      function ensureBox(){ buildBox(); var sheet=document.getElementById("settings-sheet"); if(sheet&&!sheet.__csObserved){ sheet.__csObserved=true; var mo=new MutationObserver(function(){ if(!document.getElementById("cloudSyncBox")) buildBox(); }); mo.observe(sheet,{childList:true,subtree:true}); } }
                                                                                      var _origSet=localStorage.setItem.bind(localStorage); localStorage.setItem=function(k,v){ _origSet(k,v); if(!pulling&&SYNC_KEYS.indexOf(k)>=0){ schedulePush(); } };
                                                                                      function init(){ loadScript("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2").then(function(){ sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY); ensureBox(); document.addEventListener("click",function(){ setTimeout(ensureBox,300); }); sb.auth.getSession().then(function(r){ if(r.data&&r.data.session){ onAuth(r.data.session.user); } }); sb.auth.onAuthStateChange(function(e,s){ if(s&&s.user){ onAuth(s.user); } }); }).catch(function(e){ console.warn("[sync] load failed",e); }); }
                                                                                      if(document.readyState==="loading"){ window.addEventListener("DOMContentLoaded",init); } else { init(); } })();
